// lib/mockData.ts (добавь/замени существующий массив products)

import { Product } from "./types";

export const products: Product[] = [
  {
    id: 1,
    name: 'Смеситель для кухни Grohe Eurosmart New',
    price: 12990,
    oldPrice: 15990,
    image: '/images/grohe-eurosmart-kitchen.jpg',
    category: 'Смесители',
    description: 'Однорычажный смеситель с поворотным изливом 218 мм, хром, экономайзер воды, керамический картридж. Классика для современной кухни.',
    brand: 'Grohe',
    inStock: true,
  },
  {
    id: 2,
    name: 'Унитаз-компакт Santek Алькор белый',
    price: 8490,
    image: '/images/santek-alkor-compact.jpg',
    category: 'Унитазы',
    description: 'Напольный компакт с горизонтальным выпуском, двойной слив 3/6 л, сиденье с микролифтом в комплекте, антибактериальное покрытие.',
    brand: 'Santek',
    inStock: true,
  },
  {
    id: 3,
    name: 'Ванна акриловая Ravak Rosa II 170×70 правая',
    price: 28900,
    oldPrice: 34900,
    image: '/images/ravak-rosa-bath.jpg',
    category: 'Ванны',
    description: 'Акриловая ванна с усиленным дном, эргономичная форма, антискользящее покрытие, белый глянец. Идеальна для стандартных ванных.',
    brand: 'Ravak',
    inStock: true,
  },
  {
    id: 4,
    name: 'Смеситель для ванны Hansgrohe Logis',
    price: 18990,
    image: '/images/hansgrohe-logis-bath.jpg',
    category: 'Смесители',
    description: 'Смеситель на борт ванны с душем, хром, керамический картридж, душевой набор в комплекте. Минималистичный дизайн.',
    brand: 'Hansgrohe',
    inStock: true,
  },
  {
    id: 5,
    name: 'Душевая кабина Triton Бриз 90×90',
    price: 35900,
    oldPrice: 42900,
    image: '/images/triton-briz-cabin.jpg',
    category: 'Душевые кабины',
    description: 'Закрытая кабина с высоким поддоном, раздвижные двери, тропический душ, гидромассаж 4 форсунки, подсветка.',
    brand: 'Triton',
    inStock: true,
  },
  {
    id: 6,
    name: 'Раковина подвесная Roca Gap 55 см',
    price: 12490,
    image: '/images/roca-gap-washbasin.jpg',
    category: 'Раковины',
    description: 'Компактная подвесная раковина без перелива, белый санфарфор, современный минимализм. Подходит под тумбу 50–60 см.',
    brand: 'Roca',
    inStock: true,
  },
  {
    id: 7,
    name: 'Инсталляция для унитаза Grohe Rapid SL',
    price: 22990,
    oldPrice: 27990,
    image: '/images/grohe-rapid-instal.jpg',
    category: 'Инсталляции',
    description: 'Система инсталляции с двойной кнопкой смыва, рама 114 см, шумоизоляция, подходит для подвесных унитазов.',
    brand: 'Grohe',
    inStock: true,
  },
  {
    id: 8,
    name: 'Смеситель для раковины Iddis Bild',
    price: 6990,
    image: '/images/iddis-bild-faucet.jpg',
    category: 'Смесители',
    description: 'Однорычажный смеситель для умывальника, хром, аэратор, гибкая подводка. Отличное соотношение цена/качество.',
    brand: 'Iddis',
    inStock: true,
  },
  {
    id: 9,
    name: 'Полотенцесушитель водяной AM.PM Grace 60×50',
    price: 14990,
    oldPrice: 18900,
    image: '/images/ampm-grace-towel.jpg',
    category: 'Полотенцесушители',
    description: 'Лесенка из нержавеющей стали, боковое подключение 1/2", матовый черный, 9 перекладин. Стильный и функциональный.',
    brand: 'AM.PM',
    inStock: false,
  },
  {
    id: 10,
    name: 'Унитаз подвесной Sanita Luxe Best',
    price: 15990,
    image: '/images/sanita-luxe-hanging.jpg',
    category: 'Унитазы',
    description: 'Подвесной унитаз безободковый (rimless), с микролифтом, быстросъёмное сиденье, антибактериальное покрытие.',
    brand: 'Sanita Luxe',
    inStock: true,
  },
];


export const categories = [
  'Смесители',
  'Унитазы',
  'Ванны',
  'Душевые кабины',
  'Раковины',
  'Инсталляции',
  'Полотенцесушители',
];